<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Patient List Export - {{ ucfirst($type) }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            line-height: 1.6;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
        }
        .export-info {
            margin-bottom: 20px;
            padding: 10px;
            background-color: #f5f5f5;
            border-left: 4px solid #1976D2;
        }
        .patient-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        .patient-table th,
        .patient-table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        .patient-table th {
            background-color: #1976D2;
            color: white;
            font-weight: bold;
        }
        .patient-table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .patient-table tr:hover {
            background-color: #f5f5f5;
        }
        .summary-section {
            margin-top: 30px;
            padding: 15px;
            background-color: #e3f2fd;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Patient List Export</h1>
        <h2>{{ ucfirst($type) }} Report</h2>
        <p>Generated on: {{ $export_date }}</p>
    </div>

    <div class="export-info">
        <strong>Export Information:</strong><br>
        Report Type: {{ ucfirst($type) }}<br>
        Total Patients: {{ $patients->count() }}<br>
        Export Date: {{ $export_date }}
    </div>

    @if($patients->count() > 0)
        <table class="patient-table">
            <thead>
                <tr>
                    <th>Patient No</th>
                    <th>Full Name</th>
                    <th>Birthdate</th>
                    <th>Age</th>
                    <th>Sex</th>
                    <th>Mobile No</th>
                    <th>Address</th>
                    @if($type === 'detailed')
                        <th>Occupation</th>
                        <th>Civil Status</th>
                        <th>Religion</th>
                    @endif
                    @if($type === 'medical_history')
                        <th>Drug Allergies</th>
                        <th>Past Medical History</th>
                    @endif
                    <th>Registration Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach($patients as $patient)
                    <tr>
                        <td>{{ $patient->patient_no }}</td>
                        <td>{{ $patient->full_name }}</td>
                        <td>{{ $patient->birthdate ? $patient->birthdate->format('Y-m-d') : 'N/A' }}</td>
                        <td>{{ $patient->age ?? 'N/A' }}</td>
                        <td>{{ ucfirst($patient->sex ?? 'N/A') }}</td>
                        <td>{{ $patient->mobile_no ?? 'N/A' }}</td>
                        <td>{{ $patient->present_address ?? 'N/A' }}</td>
                        @if($type === 'detailed')
                            <td>{{ $patient->occupation ?? 'N/A' }}</td>
                            <td>{{ ucfirst($patient->civil_status ?? 'N/A') }}</td>
                            <td>{{ $patient->religion ?? 'N/A' }}</td>
                        @endif
                        @if($type === 'medical_history')
                            <td>{{ $patient->drug_allergies ?? 'N/A' }}</td>
                            <td>{{ $patient->past_medical_history ?? 'N/A' }}</td>
                        @endif
                        <td>{{ $patient->created_at ? $patient->created_at->format('Y-m-d H:i:s') : 'N/A' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div class="summary-section">
            <h3>Export Summary</h3>
            <p><strong>Total Patients Exported:</strong> {{ $patients->count() }}</p>
            <p><strong>Export Type:</strong> {{ ucfirst($type) }}</p>
            <p><strong>Generated On:</strong> {{ $export_date }}</p>
            <p><strong>Report Generated By:</strong> St. James Clinic Management System</p>
        </div>
    @else
        <div class="summary-section">
            <h3>No Patients Found</h3>
            <p>No patients were found matching the export criteria.</p>
        </div>
    @endif
</body>
</html>
