<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Patient Summary - {{ $patient->full_name ?? 'Unknown Patient' }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            line-height: 1.6;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
        }
        .section {
            margin-bottom: 25px;
        }
        .section-title {
            background-color: #1976D2;
            color: white;
            padding: 10px;
            margin: 0 0 15px 0;
            font-weight: bold;
            font-size: 16px;
        }
        .field-row {
            display: flex;
            margin-bottom: 8px;
            border-bottom: 1px solid #eee;
            padding: 5px 0;
        }
        .field-label {
            font-weight: bold;
            width: 200px;
            flex-shrink: 0;
        }
        .field-value {
            flex: 1;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Patient Summary Report</h1>
        <h2>{{ $patient->full_name ?? 'Unknown Patient' }} ({{ $patient->patient_no ?? 'N/A' }})</h2>
        <p>Generated on: {{ now()->format('F d, Y \a\t g:i A') }}</p>
    </div>

    <div class="section">
        <div class="section-title">Patient Information</div>
        <div class="field-row">
            <div class="field-label">Patient Number:</div>
            <div class="field-value">{{ $patient->patient_no ?? 'N/A' }}</div>
        </div>
        <div class="field-row">
            <div class="field-label">Full Name:</div>
            <div class="field-value">{{ $patient->full_name ?? 'N/A' }}</div>
        </div>
        <div class="field-row">
            <div class="field-label">Birthdate:</div>
            <div class="field-value">{{ $patient->birthdate ? $patient->birthdate->format('Y-m-d') : 'N/A' }}</div>
        </div>
        <div class="field-row">
            <div class="field-label">Age:</div>
            <div class="field-value">{{ $patient->age ?? 'N/A' }}</div>
        </div>
        <div class="field-row">
            <div class="field-label">Sex:</div>
            <div class="field-value">{{ ucfirst($patient->sex ?? 'N/A') }}</div>
        </div>
        <div class="field-row">
            <div class="field-label">Mobile Number:</div>
            <div class="field-value">{{ $patient->mobile_no ?? 'N/A' }}</div>
        </div>
        <div class="field-row">
            <div class="field-label">Address:</div>
            <div class="field-value">{{ $patient->present_address ?? 'N/A' }}</div>
        </div>
    </div>

    <div class="section">
        <div class="section-title">Export Information</div>
        <div class="field-row">
            <div class="field-label">Export Date:</div>
            <div class="field-value">{{ now()->format('Y-m-d H:i:s') }}</div>
        </div>
        <div class="field-row">
            <div class="field-label">Generated By:</div>
            <div class="field-value">St. James Clinic Management System</div>
        </div>
    </div>
</body>
</html>
